export const products = [
    {
      id: 1,
      name: "BAHRAIN INTERNASIONAL CIRCUIT",
      category: "Cirkuit",
      price: 17,
      image: "/images/sirkuit/1.png",
      isCart: false,
      description: "This shirt features a vibrant and eye-catching color and a solid pattern that will give you a happy feeling. Its long sleeve design makes it an ideal choice for men. The turn-down collar adds to comfort and stylish look. Its versatile design and great fit make it an ideal choice for casual occasions. Specifications Style: Casual Sleeve Style: Regular Sleeve Length(cm): Full Shirts Type: Casual Shirts Pattern Type: Solid Origin: CN(Origin) Model Number: C6112 Material: Cotton Item T",
    },
    {
      id: 2,
      name: "Melbourne Grand Prix Circuit",
      category: "Cirkuit",
      price: 20,
      image: "/images/sirkuit/2.png",
      isCart: false,
      description: "Regular fit Denim design Classic collar Long buttoned sleeve Patch pocket on the chest Button up The model is 187 cm tall and is wearing a size M",
    },
    {
      id: 3,
      name: "Red Bull Ring Circuit Of Spielberg",
      category: "Circuit",
      price: 17,
      image: "/images/sirkuit/3.png",
      isCart: false,
      description: "Navy Blue Preppy Long Sleeve Polyester Plaid Shirt Non-Stretch Spring/Fall Men Tops",
    },
    {
      id: 4,
      name: "Suzuka International Circuit",
      category: "Circuit",
      price: 16,
      image: "/images/sirkuit/4.png",
      isCart: false,
      description: "Rugged, functional, and to the point. The Operator Utility Shirt has a military look with a metropolitan fit and finish. The durable stone gray cotton shirt weight canvas is sure to be a favorite back to well-worn denim.",
    },
    {
      id: 5,
      name: "Circuit Of the Amaricas",
      category: "Circuit",
      price: 10,
      image: "/images/sirkuit/5.png",
      isCart: false,
      description: "White Casual Short Sleeve Cotton Plain Top Embellished Non-Stretch Summer Men Tops",
    },
    {
      id: 6,
      name: "Monte Carlo de Monaco GP",
      category: "Street Circuit",
      price: 10,
      image: "/images/sirkuit/sc1.png",
      isCart: false,
      description: "White Casual Short Sleeve Cotton Plain Top Embellished Non-Stretch Summer Men Tops",
    },
    {
      id: 7,
      name: "Las Vegas International Street Circuit",
      category: "Street Circuit",
      price: 10,
      image: "/images/sirkuit/sc2.png",
      isCart: false,
      description: "White Casual Short Sleeve Cotton Plain Top Embellished Non-Stretch Summer Men Tops",
    },
    {
      id: 8,
      name: "Marina Bay Street Circuit",
      category: "Circuit",
      price: 10,
      image: "/images/sirkuit/sc3.png",
      isCart: false,
      description: "White Casual Short Sleeve Cotton Plain Top Embellished Non-Stretch Summer Men Tops",
    }
  ];